/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/JSP_Servlet/Servlet.java to edit this template
 */
package com.WEB;

import com.DAO.InventoryDAO;
import com.Model.InventoryItem;
import com.Model.User;
import java.io.IOException;
import java.sql.SQLException;
import java.util.List;
import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

@WebServlet(name = "InventoryServlet", urlPatterns = {
    "/InventoryServlet",
    "/listInventory",
    "/newInventory",
    "/insertInventory",
    "/editInventory",
    "/updateInventory",
    "/deleteInventory"
})
public class InventoryServlet extends HttpServlet {

    private InventoryDAO inventoryDAO;

    public void init() {
        inventoryDAO = new InventoryDAO();
    }

    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods.">
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        String action = request.getServletPath();

        try {
            switch (action) {
                case "/newInventory":
                    showNewForm(request, response);
                    break;
                case "/insertInventory":
                    insertInventory(request, response);
                    break;
                case "/deleteInventory":
                    deleteInventory(request, response);
                    break;
                case "/editInventory":
                    showEditForm(request, response);
                    break;
                case "/updateInventory":
                    updateInventory(request, response);
                    break;
                default:
                    listInventory(request, response);
                    break;
            }
        } catch (SQLException ex) {
            throw new ServletException(ex);
        }
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        doGet(request, response);
    }

    // =========================================================================
    //                            MAIN ACTIONS
    // =========================================================================

    private void listInventory(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException, SQLException {
        
        // Security Check
        HttpSession session = request.getSession();
        User currentUser = (User) session.getAttribute("currentUser");
        if (currentUser == null) {
            response.sendRedirect("index.jsp");
            return;
        }

        List<InventoryItem> listInventory = inventoryDAO.selectAllItems();
        request.setAttribute("listInventory", listInventory);
        RequestDispatcher dispatcher = request.getRequestDispatcher("InventoryList.jsp");
        dispatcher.forward(request, response);
    }

    private void showNewForm(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        RequestDispatcher dispatcher = request.getRequestDispatcher("NewInventory.jsp");
        dispatcher.forward(request, response);
    }

    private void insertInventory(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException, SQLException {
        
        // Note: ItemID is auto-generated by DB Trigger (I0001...), so we don't pass it here
        String iName = request.getParameter("iName");
        String category = request.getParameter("category");
        String unit = request.getParameter("unit");
        int quantityAvailable = Integer.parseInt(request.getParameter("quantityAvailable"));
        int threshold = Integer.parseInt(request.getParameter("threshold"));

        InventoryItem newItem = new InventoryItem();
        newItem.setIName(iName);
        newItem.setCategory(category);
        newItem.setUnit(unit);
        newItem.setQuantityAvailable(quantityAvailable);
        newItem.setThreshold(threshold);

        inventoryDAO.insertInventoryItem(newItem);
        response.sendRedirect("listInventory");
    }

    private void showEditForm(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        String id = request.getParameter("id");
        InventoryItem existingItem = inventoryDAO.selectItemByID(id);
        RequestDispatcher dispatcher = request.getRequestDispatcher("EditInventoryForm.jsp");
        request.setAttribute("item", existingItem);
        dispatcher.forward(request, response);
    }

    private void updateInventory(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException, SQLException {
        
        String id = request.getParameter("id");
        String iName = request.getParameter("iName");
        String category = request.getParameter("category");
        String unit = request.getParameter("unit");
        int quantityAvailable = Integer.parseInt(request.getParameter("quantityAvailable"));
        int threshold = Integer.parseInt(request.getParameter("threshold"));

        InventoryItem item = new InventoryItem(id, iName, category, unit, quantityAvailable, threshold);
        
        inventoryDAO.updateInventoryItem(item);
        response.sendRedirect("listInventory");
    }

    private void deleteInventory(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException, SQLException {
        String id = request.getParameter("id");
        inventoryDAO.deleteInventoryItem(id);
        response.sendRedirect("listInventory");
    }

    @Override
    public String getServletInfo() {
        return "Inventory Management Servlet";
    }// </editor-fold>
}